#!/sbin/nft -f

# ============================================================================>

flush ruleset

# ============================================================================>

# Filter both IPv4 and IPv6 packets
table inet filter {
	# Incoming packets that are addressed to this computer
	chain INPUT {
		type filter hook input priority filter; policy drop;

		ct state invalid counter drop \
			comment "Drop invalid packets"		

		ct state established,related counter accept \
			comment "Accept incoming packets"

		iif lo accept comment "Accept loopback packets"

		ip protocol icmp counter accept \
			comment "Accept ICMP (IPv4) packets"

		meta l4proto ipv6-icmp counter accept \
			comment "Accept ICMP (IPv6) packets"

		tcp dport 22 accept comment "Accept SSH connections"

		counter comment "Drop incoming packets"
	}
	
	# Incoming packets that are forwarded to another computer
	chain FORWARD {
		type filter hook forward priority filter; policy drop;
	
		counter comment "Drop forwarded packets"
	}
	
	# Outbound packets that originated from this computer
	chain OUTPUT {
		type filter hook output priority filter; policy accept;

		counter comment "Accept outbound packets"
	}
} 

# ============================================================================>
